export default [
  "Generating terrain...",
  "i solemnly swear that i am up to no good",
  "Switching sides",
  "Is this thing on..?",
  "Preparing Final Form",
  "ULTIMATE IS READY!",
  "Activating Witch Time...",
  "Entering cheat codes",
  "Pressing random buttons",
  "Caution: Contents Spicy",
  "l o a d i n g a e s t h e t i c s",
  "Adding Hidden Agendas",
  "Aligning Covariance Matrices",
  "Applying Feng Shui Shaders",
  "Building Data Trees",
  "Bureacritizing Bureaucracies",
  "Calculating Inverse Probability Matrices",
  "Deciding What Message to Display Next",
  "Destabilizing Economic Indicators",
  "Determining Width of Blast Fronts",
  "Downloading Satellite Terrain Data",
  "Factoring Pay Scale",
  "Generating Jobs",
  "Implementing Impeachment Routine",
  "Increasing Accuracy of RCI Simulators",
  "Increasing Magmafacation",
  "Initializing Robotic Click-Path AI",
  "Iterating Cellular Automata",
  "Lecturing Errant Subsystems",
  "Modeling Object Components",
  "Normalizing Power",
  "Populating Lot Templates",
  "Realigning Alternate Time Frames",
  "Reconfiguring User Mental Processes",
  "Resolving GUID Conflict",
  "Retracting Phong Shader",
  "Retrieving from Back Store",
  "Routing Neural Network Infanstructure",
  "Searching for Llamas",
  "Sequencing Particles",
  "Setting Advisor Moods",
  "Setting Inner Deity Indicators",
  "Setting Universal Physical Constants",
  "Speculating Stock Market Indices",
  "Splatting Transforms",
  "Stratifying Ground Layers",
  "Synthesizing Gravity",
  "Unable to Reveal Current Activity",
  "Weathering Buildings",
  "Zeroing Crime Network"
];
